### ISSUE TITLE
CUDA runs out of memory

### ISSUE THREAD

**Issue by ANUSHAJAY** [chirag126/VOG#5]
Hi, 
While running this code, because the gradients w.r.t all images is of the dimension [50000,32,32,3], it seems that my CUDA is running out of memory very soon .

**Comment by chirag-agarwall** [comment]
Hi Anushajay,

Thank you for your interest in our work. Memory issues can be a bottleneck for models with large batch sizes. I would suggest using smaller batch sizes for storing gradients.
